CREATE TABLE SAMPLE_TABLE_V16 (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DESCRIPTION TEXT
);
